<?php

/**
 * hook_menu()
 */
function oa_worktracker_reports_menu() {
  $items['tasks'] = [
    'title' => 'Lista de tareas',
    'page callback' => 'tasks',
    'access arguments' => [
      'access content',
    ],
  ];
  $items['task_detail'] = [
    'title' => 'Detalle de la tarea',
    'page callback' => 'task_detail',
    'access arguments' => [
      'access content',
    ],
  ];
  return $items;
}

/**
 * All tasks callback
 */
function tasks() {
  $path = Drupal_get_path('module', 'oa_worktracker_reports');
  oa_angular_add(array('sanitize', 'cookies', 'ng-modules', 'ng-treecontrol'));
  Drupal_add_js($path . '/js/tasks.js');
  Drupal_add_css($path . '/css/tasks.css');
  drupal_add_library('system', 'ui.datepicker');
  drupal_add_library('chosen', 'drupal.chosen');
  return theme('tasks');
}

/**
 * Task detail callback
 */
function task_detail() {
  $path = Drupal_get_path('module', 'oa_worktracker_reports');
  oa_angular_add(array('sanitize', 'cookies', 'ng-modules', 'ng-treecontrol'));
  Drupal_add_js($path . '/js/task_detail.js');
  Drupal_add_css($path . '/css/task_detail.css');
  drupal_add_library('system', 'ui.datepicker');
  drupal_add_library('chosen', 'drupal.chosen');
  return theme('task_detail');
}

/**
 * Implements hook_controller_api().
 */
function oa_worktracker_reports_controller_api() {
  return '2.x';
}


/**
 * hook_theme()
 */
function oa_worktracker_reports_theme() {
  return [
    'tasks' => [
      'template' => 'tasks',
    ],
    'task_detail' => [
      'template' => 'task_detail',
    ],
  ];
}


/**
 * Implements hook_theme_registry_alter().
 */
function oa_worktracker_reports_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'oa_worktracker_reports');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
